services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend-app:
    build: ./backend
    container_name: backend-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/banco_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    restart: on-failure

  frontend-app:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend-app
    restart: always
